{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "shlinkchart.fullname" . }}
  labels: {{- include "shlinkchart.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host | default "shlink.lv" | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "shlinkchart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - secretName: {{ (index .Values.ingress.tls 0).secretName | default "shlink-tls" }}
      hosts: [{{ (index .Values.ingress.hosts 0).host | default "shlink.lv" | quote }}]
{{- end }}
