apiVersion: v1
kind: Service
metadata:
  name: {{ include "shlinkchart.fullname" . }}
  labels: {{- include "shlinkchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "shlinkchart.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  
