{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink-shlinkchart-ui
  labels: {{- include "shlinkchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: shlink-shlinkchart-ui
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shlink-shlinkchart-ui
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.ui.service.targetPort | default 8080 }}
          env:
            - name: SHLINK_SERVER_URL
              value: "http://back.shlink.lv"
            - name: DEFAULT_SERVER_URL
              value: "http://back.shlink.lv"
{{- end }}
