fullnameOverride: "shlink-shlinkchart"

replicaCount: 1

image:
  repository: shlinkio/shlink
  tag: "4.4.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

ui:
  enabled: true
  replicaCount: 1
  image:
    repository: shlinkio/shlink-web-client
    tag: "4.5"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8080
  
  
env:
  db:
    host: "mariadb.shlink.svc.cluster.local"
    port: 3306
    name: "shlink"
    userKey: "DB_USER"
    passKey: "DB_PASSWORD"
  secretsExistingSecret: "shlink-app"
  dbExistingSecret: "shlink-db"

resources: {}